[package]
name = "hasher"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
crc = "2.0.0"
md2 = "0.9.0"
md4 = "0.9.0"
md5 = "0.7.0"
